blog/urls.py
from django.conf.urls import url,include
from blogCMS1 import settings
from  blog import views
urlpatterns = [
    #用户修改个人资料功能
    url(r'^edituser/(\d+)$', views.edituser),


    #文章赞、踩功能
    url(r'^updown/$', views.updown),
    url(r'^comment/$', views.comment),    #文章评论功能
    #显示文章已发表的评论，树状结构
    url(r'^commentTree/(?P<article_id>\d+)$', views.commentTree),
    url(r'^backend/$', views.backendindex),#后台管理首页
    url(r'^backend/addarticle/$', views.addarticle),#后台管理添加新文章功能
    url(r'^backend/editarticle/(\d+)$', views.editarticle),#编辑文章
    url(r'^backend/del/(\d+)', views.delarticle),#删除文章
    # 文章详情页面
    url(r'^(?P<username>.*)/article_detail/(?P<article_nid>\d+)', views.article_detail),
    # 个人站点首页，需要渲染个人分类、标签和日期的归档，所以需要用到正则
    url(r'^(?P<username>.*)/(?P<condition>tag|category|date)/(?P<para>.*)', views.homeSite),
    # 路由反向解析，在模板页面中直接用别名即可
    url(r'^(?P<username>.*)', views.homeSite, name="aaa"),
]

blogCMS1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from blog import views
from blogCMS1 import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),#Django自带

    url(r'^reg/', views.reg),  # 注册功能
    url(r'^login/', views.log_in),#登录功能
    url(r'^log_out/', views.log_out),#注销功能
    url(r'^get_validCode_img/', views.get_validCode_img),  # 验证码功能
    url(r'^index/', views.index),#首页功能
    url(r'^$', views.index),#只输入域名的情况下默认进入首页
    url(r'^cate/(?P<site_article_category>.*)/$', views.index),  # 首页的小分类
                                    #  index(requset,site_article_category=python)

    # 个人站点首页，将个人站点需要用到的路由下发到blog下的urls中
    url(r'^blog/', include('blog.urls')),#路由分发


    #media 配置：我们将网站中上传的文件放置于media文件夹中，
    #            因为该文件夹是新创建的
    #            所以我们需要在settings中进行相应配置，稍后会有配置的代码

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^uploadFile/$', views.uploadFile),#添加文章时上传图片


]

blog/models.py
from django.db import models
# Create your models here.
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息，只存放最主要的字段，继承auth模块
    """
    nid = models.BigAutoField(primary_key=True)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    telephone = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    avatar = models.FileField(verbose_name='头像', upload_to='avatar', default="/avatar/default.jpeg")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    站点信息，每个注册用户有一个自己的个人站点
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客后缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)
    # 与用户信息表一对一关联，关联字段建在blog表中
    user = models.OneToOneField(to='UserInfo', to_field='nid')

    def __str__(self):
        return self.title


class Article(models.Model):
    """
    文章表，存放着所有该用户站点发布的文章
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    #一个文章只能属于一个分类，而一个分类下有多个文章，所以外键建在文章表
    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='nid', null=True)
    #一个用户可以发表多篇文章，而一个文章只能由一个用户发表
    user = models.ForeignKey(verbose_name='所属用户', to='UserInfo', to_field='nid')
    #文章中有关键字，关键字可以看做是标签，文章与标签的关系是多对多
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),#自己建的多对多关联的第三张表
    )
    #博客园首页的总的文章大分类下的小分类，与个人站点分类无关，该分类与文章也是一对多关系
    site_article_category=models.ForeignKey("SiteArticleCategory",null=True)

    def __str__(self):
        return self.title


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField(verbose_name='文章内容', )
    #若文章表将所有文章内容存入，数据量会很大，所以我们用一个详情表存储，与文章表一对一
    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid')
    def __str__(self):
        return self.article.title


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    #与站点进行多对一关联，外键必须建在多的一方
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'category'
        ordering = ['title']


class Tag(models.Model):
    """
    标签表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')


class Article2Tag(models.Model):
    """
    文章和标签的多对多关系表，自己创第三张表的好处是可以自定义表的字段
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid')

    class Meta:
        #文章和标签联合唯一
        unique_together = [
            ('article', 'tag'),
        ]


class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    up_count = models.IntegerField(default=0)#点赞数

    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid')
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')
    #自关联，用于判断该评论是对文章的评论还是对评论的评论
    parent_comment = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论')

    def __str__(self):
        return self.content


class CommentUp(models.Model):
    """
    点评论赞表
    """

    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True)
    comment = models.ForeignKey("Comment", null=True)


class ArticleUp(models.Model):
    """
    点文章赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True)
    article = models.ForeignKey("Article", null=True)


class ArticleDown(models.Model):
    """
    点down表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True)
    article = models.ForeignKey("Article", null=True)


class SiteCategory(models.Model):
    """
    首页的大分类表，与个人站点分类无关,该分类与文章不直接绑定关系，
    因为该分类下还有小分类，小分类才与文章绑定关系

    大分类（例如计算机编程语言）——>
                小分类（例如python——>文章1
                                        文章2
                                        ……
                            java——>文章（）
                                        ……
                            c++——>文章（）
                                        ……
                            ……）

    """
    name=models.CharField(max_length=32)


    def __str__(self):
        return self.name

class SiteArticleCategory(models.Model):
    """
    首页的大分类下的小分类表，与大分类是多对一关系，与个人站点的分类无关
    """
    name=models.CharField(max_length=32)
    site_category=models.ForeignKey('SiteCategory')


    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from django.forms import widgets,ValidationError
from blog import models


class LoginForm(forms.Form):#必须继承
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label='password', max_length=100)
    def clean_username(self):#钩子函数
        if len(self.cleaned_data.get("username"))>5:
            print(self.cleaned_data.get("password"))
            return self.cleaned_data.get("username")
        else:
            raise
    def clean_password(self):
        pass
    def clean(self):
        if self.cleaned_data["password"] == self.cleaned_data["repeat_password"]:
            return self.cleaned_data

#注册页面的form组件
class RegForm(forms.Form):#必须继承
    username=forms.CharField(max_length=32,
                             min_length=5,
                             error_messages={'required':'用户名不能为空'},
                             widget=widgets.TextInput(attrs={"class":"form-control","placeholder":"请输入用户名"})
                             )
    password=forms.CharField(max_length=32,
                             min_length=6,
                             widget=widgets.PasswordInput(
                                 attrs={"class": "form-control", "placeholder": "请输入密码"}
                             ))
    repeat_pwd = forms.CharField(min_length=6, widget=widgets.PasswordInput(
        attrs={"class": "form-control", "placeholder": "请再次输入密码"}
    ))

    email = forms.EmailField(widget=widgets.EmailInput(
        attrs={"class": "form-control", "placeholder": "请输入邮箱"}
    ))

    def clean_username(self):
        """
        钩子函数,判断用户名是否已存在
        :return:
        """
        ret = models.UserInfo.objects.filter(username=self.cleaned_data.get("username"))
        if not ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户名已注册")

    def clean_password(self):
        """
        钩子函数，规定密码不能是全数字或全字母
        :return:
        """
        ret = self.cleaned_data.get("password")
        if ret.isdigit():
            raise ValidationError("密码不能全是数字")
        elif ret.isalpha():
            raise ValidationError("密码不能全是字母")
        else:
            return ret

    # def clean_validCode(self):
    #     if self.cleaned_data.get("validCode") == self.request.session.get("validCode"):
    #         return self.cleaned_data.get("validCode")
    #     else:
    #         raise ValidationError("验证码错误")

    def clean(self):
        """
        全局钩子函数，判断两次密码是否一致
        :return:
        """
        if self.cleaned_data.get("password") == self.cleaned_data.get("repeat_pwd"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")

    # def __init__(self, request, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.request = request



from blog.plugins import xss_plugin
class ArticleForm(forms.Form):

    title=forms.CharField(max_length=20,error_messages={
        "required":"不能为空",
    },widget=widgets.Input(attrs={"class":"form-control"}))

    content=forms.CharField(error_messages={
        "required":"不能为空",
    },widget=widgets.Textarea(attrs={"id":"id_content"}))

    def clean_content(self):

        html_str=self.cleaned_data.get("content")
        clean_content=xss_plugin.filter_xss(html_str)#过滤非法标签和属性
        self.cleaned_data["content"]=clean_content

        return self.cleaned_data.get("content")

templates/homeSite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} 个人首页 {% endblock %}</title>
    <script src="/static/jquery-3.2.1.min.js"></script>

    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/mycss/homeSite.css">
    <link rel="stylesheet" href="/static/mycss/article_detail.css">
    <link rel="stylesheet" href="/static/user_home_style/{{ current_user.blog.theme }}">
    <script src="/static/kindeditor/kindeditor-all.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse" id="nav">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">博客园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/blog/{{ current_user.username }}">{{ current_user.blog.title }} <span class="sr-only">(current)</span></a>
                </li>
                <li><a href="#">Link</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">首页</a></li>
                <li><a href="#">新随笔</a></li>
                <li><a href="#">联系</a></li>
                <li><a href="#">订阅</a></li>
                <li><a href="#">管理</a></li>
                {% if request.user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">

                            {{ request.user.username }}

                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/blog/{{ request.user.username }}">个人首页</a></li>
                        <li><a href="/blog/backend/">文章管理</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/log_out/">注销</a></li>
                    </ul>
                </li>
                {% else %}
                    <li><a href="/login/">请登录</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">公告</div>
                <div class="panel-body">
                    <p><b>Python开发交流群：255012808</b></p>
                    <p><b>Python开发交流群：255012808</b></p>
                    <p><b>Python开发交流群：255012808</b></p>
                    <p><b>Python技术交流群：557877767</b></p>
                    <p><b>开源Tyrion交流群：564068039</b></p>
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">个人信息</div>
                <div class="panel-body">
                    <p><img class="img-circle " src="{{ current_user.avatar.url }}" alt="" height="100" width="100"></p>

                    <h3>昵称：{{ current_user.username }}</h3>
                </div>
            </div>
            <div class="panel panel-danger">
                <div class="panel-heading">我的标签</div>
                <div class="panel-body">
                <ul class="list-group">
                    {% for foo in current_user.blog.tag_set.all %}
                        <li class="list-group-item">
                            <span class="badge">{{ foo.article_set.count }}</span>
                            <a href="/blog/{{ current_user.username }}/tag/{{ foo.nid }}">{{ foo.title }}</a>
                        </li>
{#                        <p>#}
{#                            <a href="/blog/{{ current_user.username }}/tag/{{ foo.nid }}">{{ foo.title }}({{ foo.article_set.count }})</a>#}
{#                        </p>#}
                    {% endfor %}
                </ul>

                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">随笔分类</div>
                <div class="panel-body">
                <ul class="list-group">
                    {% for foo in current_user.blog.category_set.all %}
                        <li class="list-group-item">
                            <span class="badge">{{ foo.article_set.count }}</span>
                            <a href="/blog/{{ current_user.username }}/category/{{ foo.nid }}">{{ foo.title }}</a>
                        </li>
{#                        <p>#}
{#                            <a href="/blog/{{ current_user.username }}/category/{{ foo.nid }}">{{ foo.title }}({{ foo.article_set.count }})</a>#}
{#                        </p>#}
                    {% endfor %}
                </ul>



                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">随笔档案</div>
                <div class="panel-body">
                <ul class="list-group">
                    {% for date in date_list %}
                        <li class="list-group-item">
                            <span class="badge">{{ date.1 }}</span>
<a href="/blog/{{ current_user.username }}/date/{{ date.0 }}">{{ date.0 }}{{ date.1 }}</a>                        </li>
{#                   <p>#}
{#                        <a href="/blog/{{ current_user.username }}/date/{{ date.0 }}">{{ date.0 }}({{ date.1 }})</a>#}
{#                        </p>#}

                    {% endfor %}
                </ul>





                </div>
            </div>
        </div>

            <div class="col-md-9 c1">
        {% block con %}

                {% for foo in article_list %}
                    <div class="article">
                        <div class="head">
                            <h3>
                                <a href="/blog/{{ current_user.username }}/article_detail/{{ foo.nid }}">{{ foo.title }}</a>
                            </h3>
                        </div>
                        <div class="desc">
                            {{ foo.desc }}
                        </div>
                        <div class="foot pull-right">
                            posted@ <span>{{ foo.create_time|date:"Y-m-d" }}</span>&nbsp;
                            <span>评论({{ foo.comment_count }})</span>&nbsp;
                            <span>点赞({{ foo.up_count }})</span>&nbsp;
                            <span>阅读({{ foo.read_count }})</span>

                        </div>
                        <p></p>
                    </div>
                {% endfor %}

                {% endblock %}
        </div>

    </div>
</div>

<div>

</div>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>首页</title>
    <script src="/static/jquery-3.2.1.min.js"></script>

    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/mycss/index.css">

</head>
<body>
{#导航条#}
<nav class="navbar navbar-inverse">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">博客园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    {# 用户登录状态，显示用户信息#}
                    <li class="active"><a>欢迎：</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            {{ request.user.username }}
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/blog/{{ request.user.username }}">个人首页</a></li>
                            <li><a href="/blog/backend/">文章管理</a></li>
                            <li><a href="/blog/edituser/{{ request.user.nid }}">修改资料</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/log_out/">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    {#    未登录状态，显示登录、注册按钮#}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/reg/">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{#内容#}
<div class="container">
    <div class="row">
        <div class="left1 col-md-2">
        {#  左侧菜单#}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">网站分类</h3>
                </div>
                <div class="panel-body">
                    {% for cate in cate_list %}
                    {#    文章大分类归档#}
                        <div class="panel panel-info menu">
                            <div class="panel-heading ">
                                <h3 class="panel-title">
                                    {{ cate.name }}
                                </h3>
                            </div>
                            <div class="panel-body hides">
                                {% for sitearticlecategory in cate.sitearticlecategory_set.all %}
                                {# 文章小分类#}
                                    <p><a href="/cate/{{ sitearticlecategory.name }}">{{ sitearticlecategory.name }}</a>
                                    </p>
                                {% endfor %}
                            </div>
                        </div>

                    {% endfor %}
                </div>
            </div>
        </div>
        {#    文章显示部分#}
        <div class="middle1 col-md-8">
            {% for article in article_list %}
                <div class="article">
                    <div class="articlt-head">
                        <a href="/blog/{{ article.user.username }}/article_detail/{{ article.nid }}">{{ article.title }}</a>
                    </div>
                    <div class="content row">
                        <div class="col-md-2">
                        {#  用户头像#}
                            <a href="{% url 'aaa'  article.user.username %}"><img src="{{ article.user.avatar.url }}"
                                                                                  alt="" width="100" height="100"></a>
                        </div>
                        <div class="col-md-10">
                            {{ article.desc }}
                        </div>
                    </div>
                    <div class="pub-info row">{#发布信息#}
                        <a href="/blog/{{ article.user.username }}">
                            {{ article.user.username }}&nbsp;&nbsp;
                        </a>
                        <span>发布于</span>
                        {{ article.user.create_time|date:"Y-m-d H:i" }}&nbsp;&nbsp;
                        <a href="/blog/{{ article.user.username }}/article_detail/{{ article.nid }}"><span
                                class="glyphicon glyphicon-comment"></span>评论({{ article.comment_count }})</a>
                        <a href="/blog/{{ article.user.username }}/article_detail/{{ article.nid }}"><span
                                class="glyphicon glyphicon-thumbs-up"></span>点赞({{ article.up_count }})</a>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="right1 col-md-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>


        </div>
    </div>
</div>


<script>
    $('.menu').mouseover(function () {
{#        鼠标移动到大分类上时显示它所属的小分类#}
        $(this).children().slideDown(300)
    }).mouseleave(function () {
{#        鼠标从大分类上移开时隐藏它所属的小分类#}
        $(this).children(".panel-body").slideUp(300)
    })


</script>


</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>注册</title>
        <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
        <script src="/static/jquery-3.2.1.min.js"></script>
        <link rel="stylesheet" href="/static/mycss/reg.css">
        <script src="/static/js/jquery.cookie.js"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="">
                {% csrf_token %}{#Django自带的防止攻击的中间件#}
                <div class="form-group">
                    <label for="username">用户名：</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label for="password">密码：</label>
                    {{ form.password }}
                </div>
                <div class="form-group">
                    <label for="repeat_pwd">确认密码：</label>
                    {{ form.repeat_pwd }}
                </div>
                <div class="form-group">
                    <label for="email">邮箱：</label>
                    {{ form.email }}
                </div>
                <div class="form-group picDiv">
                    <label for="picBtn">头像：</label>
                    <img id="pic" class="pic" src="/static/img/default.png" alt="">
                    <input id="picBtn" type="file" class="picBtn">
                </div>
                <div class="sub" style="padding-top: 50px">
                <input type="button" value="submit" class="btn btn-primary" id="subBtn"><span class="error"></span>
                </div>
            </form>

        </div>
    </div>
</div>

<script>
    // 头像预览,固定代码

    $("#picBtn").change(function () {
        var ele_file=$(this)[0].files[0];  //this.files
        var reader=new FileReader();
        reader.readAsDataURL(ele_file);
        reader.onload=function () {
            $("#pic")[0].src=this.result
        }

    });

    // ajax提交数据
    $("#subBtn").click(function () {

        var formdata=new FormData();
        formdata.append("username",$("#id_username").val());
        formdata.append("password",$("#id_password").val());
        formdata.append("repeat_pwd",$("#id_repeat_pwd").val());
        formdata.append("email",$("#id_email").val());
        formdata.append("pic",$("#picBtn")[0].files[0]);

        $.ajax({
            url:"/reg/",
            type:'POST',
            data:formdata,
            contentType:false,
            processData:false,
            headers:{"X-CSRFToken":$.cookie('csrftoken')},//中间件的值，必须写
            success:function (data) {
                  console.log(data);
                var data=JSON.parse(data);//将后端传来的json字符串转成js字符串

                if (data.user){
                    // 注册成功自动跳转至登录页面
                    location.href="/login/"
                }
                else {
                    // 查看错误信息
                    console.log(data.errorsList);

                   $.each(data.errorsList,function (i,j) {
                       console.log(i,j);
                        // 将错误信息打印到相对应的输入框下仿
                       $span=$("<span>");
                       $span.addClass("pull-right").css("color","red");
                       $span.html(j[0]);
                       $("#id_"+i).after($span).parent().addClass("has-error")

                       if (i=="__all__"){
                           // 全局钩子捕捉到错误
                            $("#id_repeat_pwd").after($span)
                       }
                   })
                }
            }
        })
    })
</script>
</body>
</html>